# Generated by Django 4.0.6 on 2022-07-24 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('noteapp', '0002_alter_note_body_alter_note_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='body',
        ),
    ]
