# Generated by Django 4.0.6 on 2022-07-25 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('like', models.IntegerField(default=0)),
            ],
        ),
    ]
